#!/usr/bin/env bash

# This script is installed from https://github.com/waterlink/secrets
# LICENSE: MIT. See: https://github.com/waterlink/secrets/blob/master/LICENSE.txt

ENCRYPTION_ALGO=${ENCRYPTION_ALGO:-aes-256-cbc}

-print-usage() {
if ! eval "[[ $* ]]"; then
  echo -e "$USAGE"
  echo "Not enough arguments provided"
  exit 1
fi
}

-mktemp() {
mktemp -dt "$(basename -- $0).XXXXXXXXXX"
}

-output-flag() {
if [[ "$1" = "-" ]]; then
  local output_flag=""
else
  local output_flag="-out $1"
fi

echo $output_flag
}

gen-key() {
  local USAGE="USAGE: $0 gen-key KEYFILENAME - Generate new symmetric key"
  -print-usage $# -eq 1

  local keyfilename=$1
  openssl rand -base64 2048 > $keyfilename
}

enc() {
  local USAGE="USAGE: $0 enc FILENAME OUTPUT KEYFILENAME - Encrypt FILENAME => OUTPUT with key KEYFILENAME"
  -print-usage $# -eq 3

  local filename=$1
  local output=$2
  local keyfilename=$3
  openssl enc -in $filename $(-output-flag $output) -e -$ENCRYPTION_ALGO -k file:$keyfilename
}

dec() {
  local USAGE="USAGE: $0 dec FILENAME OUTPUT KEYFILENAME - Decrypt FILENAME => OUTPUT with key KEYFILENAME"
  -print-usage $# -eq 3

  local filename=$1
  local output=$2
  local keyfilename=$3
  openssl enc -in $filename $(-output-flag $output) -d -$ENCRYPTION_ALGO -k file:$keyfilename
}

edit() {
  local USAGE="USAGE: $0 edit FILENAME KEYFILENAME - Edit encrypted file with your favorite editor (EDITOR environment variable)"
  -print-usage $# -eq 2

  local filename=$1
  local output="$(-mktemp)/$(basename -- $filename).tmp"
  local keyfilename=$2

  dec $filename $output $keyfilename && \
    $EDITOR $output && \
    enc $output $filename $keyfilename && \
    rm $output
}

source() {
  local USAGE="USAGE: $0 source FILENAME KEYFILENAME ARGS... - Source encrypted file with environment variables and run specified command"
  -print-usage $# -gt 2

  local filename=$1
  local keyfilename=$2
  local output=-

  shift
  shift

  eval $(dec $filename $output $keyfilename)
  $*
}

read -d '' USAGE << EOF
USAGE: $0 command ARGS...

Available commands:
gen-key - Generate new symmetric key
enc     - Encrypt file
dec     - Decrypt file
edit    - Edit encrypted file
source  - Source encrypted file with environment variables and run provided script
EOF

-print-usage $# -gt 0

command=$1
shift

$command $*
